apiVersion: v1
kind: ConfigMap
metadata:
  name: musicapi
  namespace: ns-musicapi
data:
  dbname: evergreen_music_db
  dbuser: root
  serverport: "8081"
  dbhost: mysql-api.ns-musicapi.svc.cluster.local:3306