apiVersion: v1
kind: ConfigMap
metadata:
  name: musicapi
  namespace: ns-musicapi
data:
  dbname: evergreen_music_db
  dbuser: farra
  serverport: "8081"
  dbhost: "10.20.0.7" #mysql-api.ns-musicapi.svc.cluster.local:3306