name: "[MUSIC-API][STAGING] Deployment"

on:
    push :
        branches:
        - main

env: 
    DOCKER_REGISTRY: farrasyakila/music-app-1
    DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    JSON_KEY_GCP: ${{ secrets.JSON_KEY_GCP }}

jobs:
    build-and-push:
        name: MUSIC-API 
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the gcloud cli
              uses: google-github-actions/setup-gcloud@v2

            - name: Get git SHA
              run: |
                TAG=$(git rev-parse --short HEAD)
                echo "TAG=$TAG" >> $GITHUB_ENV

            # - name: Build & Push
            #   run: |
            #     set -x
            #     DOCKER_IMAGE="$DOCKER_REGISTRY:$TAG" >> $GITHUB_ENV
            #     cd code/
            #     docker build -t $DOCKER_IMAGE .
            #     docker login -u farrasyakila -p $DOCKER_TOKEN
            #     docker push $DOCKER_IMAGE

            - name: Deploy to GKE
              env:
                JSON_KEY_GCP: ${{ secrets.JSON_KEY_GCP }}
              run: |
                set -x
                echo "$JSON_KEY_GCP" | base64 --decode > ${HOME}/key.json
                gcloud auth activate-service-account --key-file=${HOME}/key.json
                export USE_GKE_GCLOUD_AUTH_PLUGIN=true
                gcloud components install gke-gcloud-auth-plugin
                gcloud container clusters get-credentials default --region asia-southeast2 --project learn-with-farra
                cd deployment/
                kubectl version
                # sed -i "s|farrasyakila/music-app-1|${DOCKER_IMAGE}|" musicapi-deployment.yaml
                ls