name: "[MUSIC-API][STAGING] Deployment"

on:
    push :
        branches:
        - main

env: 
    DOCKER_REGISTRY: farrasyakila/music-app-1
    DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    JSON_KEY_GCP: ${{ secrets.JSON_KEY_GCP }}

jobs:
    build-and-push:
        name: MUSIC-API 
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3


            - name: install the gcloud cli
              uses: google-github-actions/setup-gcloud@v2
              with:
                project_id: "learn-with-farra"
                service_account_key: ${{ secrets.JSON_KEY_GCP }}
                install_components: 'gke-gcloud-auth-plugin'
                export_default_credentials: true

            - name: Get git SHA
              run: |
                TAG=$(git rev-parse --short HEAD)
                echo "TAG=$TAG" >> $GITHUB_ENV

            # - name: Build & Push
            #   run: |
            #     set -x
            #     DOCKER_IMAGE="$DOCKER_REGISTRY:$TAG" >> $GITHUB_ENV
            #     cd code/
            #     docker build -t $DOCKER_IMAGE .
            #     docker login -u farrasyakila -p $DOCKER_TOKEN
            #     docker push $DOCKER_IMAGE

            - name: Deploy to GKE
              env:
                GOOGLE_PROJECT: "learn-with-farra"
              run: |
                cd deployment/
                kubectl version
                gcloud container clusters get-credentials default --region asia-southeast2 --project learn-with-farra
                # sed -i "s|farrasyakila/music-app-1|${DOCKER_IMAGE}|" musicapi-deployment.yaml
                ls