name: "[MUSIC-API][STAGING] Deployment"

on:
    push :
        branches:
        - main

env: 
    DOCKER_REGISTRY: farrasyakila/music-app-1
    DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:
    build-and-push:
        name: MUSIC-API 
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup gcloud
              uses: google-github-actions/setup-gcloud@v1

            - name: gcloud login
              run: gcloud auth login --cred-file=key.json

            - name: Get git SHA
              run: |
                TAG=$(git rev-parse --short HEAD)
                echo "TAG=$TAG" >> $GITHUB_ENV

            - name: Build & Push
              run: |
                DOCKER_IMAGE="$DOCKER_REGISTRY:$TAG" >> $GITHUB_ENV
                cd code/
                docker build -t $DOCKER_IMAGE .
                docker login -u farrasyakila -p $DOCKER_TOKEN
                docker push $DOCKER_IMAGE

            - name: Deploy to GKE
              run: |
                cd deployment/
                ls