name: "[MUSIC-API][STAGING] Deployment"

on:
    push :
        branches:
        - main

env: 
    DOCKER_REGISTRY: farrasyakila/music-app-1
    DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    JSON_KEY_GCP: ${{ secrets.JSON_KEY_GCP }}

jobs:
    build-and-push:
        name: MUSIC-API 
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
              with:
                service_account_key: ${{ secrets.JSON_KEY_GCP }}
                project_id: "learn-with-farra"

            - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
              with:
                cluster_name: "default"
                location: "asia-southeast2"
                credentials: ${{ secrets.JSON_KEY_GCP }}

            # - name: Setup gcloud
            #   uses: google-github-actions/setup-gcloud@v1

            # - name: gcloud login
            #   run: gcloud auth login --cred-file=key.json

            - name: Get git SHA
              run: |
                TAG=$(git rev-parse --short HEAD)
                echo "TAG=$TAG" >> $GITHUB_ENV

            # - name: Build & Push
            #   run: |
            #     set -x
            #     DOCKER_IMAGE="$DOCKER_REGISTRY:$TAG" >> $GITHUB_ENV
            #     cd code/
            #     docker build -t $DOCKER_IMAGE .
            #     docker login -u farrasyakila -p $DOCKER_TOKEN
            #     docker push $DOCKER_IMAGE

            - name: Deploy to GKE
              run: |
                gcloud auth login --cred-file=key.json
                gcloud config set project learn-with-farra
                cd deployment/
                kubectl version
                gcloud container clusters get-credentials default --region asia-southeast2 --project learn-with-farra
                # sed -i "s|farrasyakila/music-app-1|${DOCKER_IMAGE}|" musicapi-deployment.yaml
                ls